language: perl
perl:
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.10"
env:
  - "HARNESS_OPTIONS=j6"
install:
  - "cpanm -n JSON LWP::UserAgent Exception::Class"
  - "cpanm -n --installdeps ."
notifications:
email: false